services:
  api:
    image: docker.io/${DOCKER_USER}/hightech-api:latest
    container_name: hightech-api
    restart: always
    ports:
      - "5000:86"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 0
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hightech-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
